# Generated by Django 6.0.6 on 2026-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la venta', null=True),
        ),
    ]
